[versions]
kotlin = "2.2.21"

[libraries]
kotlin-test-junit5 = { group = "org.jetbrains.kotlin", name = "kotlin-test-junit5" }
junit-platform-launcher = { group = "org.junit.platform", name = "junit-platform-launcher" }
assertj-core = { group = "org.assertj", name = "assertj-core", version = "3.26.3" }

[bundles]
test = ["kotlin-test-junit5", "junit-platform-launcher", "assertj-core"]

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
